version: '3.7'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: db-postgis-staging
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ufficiourbanistica

  website:
    image: maxdragonheart/${PROJECT_NAME}
    build:
      context: ./project
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_PORT: ${PROJECT_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    container_name: website-staging
    restart: always
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - website-static-folder:/app/web/static-folder
      - website-media-folder:/app/web/media-folder
      - website-logs:/app/web/logs
      - website-fixtures:/app/web/project/fixtures
    depends_on:
      - db
    networks:
      - ufficiourbanistica

volumes:
  db-data:
  website-static-folder:
  website-media-folder:
  website-logs:
  website-fixtures:

networks:
  ufficiourbanistica:
    driver: bridge